routes/web.php
    $state= "state";
    $country= "SA";
    $postcode="12345";
    $customerGivenName=$user->first_name;
    $customerSurName=$user->first_name.$user->mobile;
    $PaymentBrandId = 3 ;
    if($PaymentBrandId == 0 || $PaymentBrandId == 2){ // visa , stc
        $entityId=config('constants.Payment.VisaEntityID'); //test -- VisaEntityID
        $entityId="8ac7a4c78694e687018697314f3e02f4"; //test -- VisaEntityID
    }
    else if($PaymentBrandId == 1){ //mada
        $entityId=config('constants.Payment.MadaEntityID'); //test -- MadaEntityID
        $entityId="8ac7a4c78694e68701869731bae102f9"; //test -- MadaEntityID
    }
    else if($PaymentBrandId == 3){ //  apple pay
        $entityId=config('constants.Payment.ApplePayEntityID'); //test -- apple pay   "8ac7a4c87edd1a80017ede0f92940431";//
    }
    $url = "https://oppwa.com/v1/checkouts";
    //$url = "https://test.oppwa.com/v1/checkouts"; //test
    $data = "entityId=".$entityId.
        "&amount=". $amount .
        "&currency=SAR&paymentType=DB&merchantTransactionId=".$merchantTransactionId.
        "&customer.email=".$email."&billing.street1=".$street1."&billing.city=".$city."&billing.state=".$state.
        "&billing.country=".$country."&billing.postcode=".$postcode;
    if($PaymentBrandId != 2 && $PaymentBrandId != 3){
        $data .="&createRegistration=true";
    }
    if($PaymentBrandId == 3){
        $data = "entityId=".$entityId.
            "&amount=". $amount .
            "&currency=SAR&paymentType=DB&merchantTransactionId=".$merchantTransactionId.
            "&customer.email=".$email."&billing.street1=".$street1."&billing.city=".$city."&billing.state=".$state.
            "&billing.country=".$country."&billing.postcode=".$postcode;
    }


    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_HTTPHEADER, array(
        'Authorization:Bearer OGFjZGE0Y2U3YTgxMzUwOTAxN2E4MTY2MzM3MjAxZDR8ejkzOEdFN2o1Tg=='));
    // curl_setopt($ch, CURLOPT_HTTPHEADER, array(
    //     'Authorization:Bearer OGFjN2E0Yzc3NjQxYjEzMDAxNzY0MjliMDkyODA1ZmJ8SFl3NlB3V3pzSw=='));
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    $responseData = curl_exec($ch);


    if(curl_errno($ch)) {
        return response()->json(['status' => false, 'message' => __('Please try again'),'$responseData'=>$responseData], 200);
    }
    curl_close($ch);
    $Vat = 14;
    $checkoutId = json_decode($responseData);

    return $checkoutId ;
    if($checkoutId->result->code == "000.200.100"){
        $checkoutId = $checkoutId->id;
        $ReturnedURL = config('global.WebsiteURL')."public/en/hyperpay?checkoutId=".$checkoutId."&user_id=".$userID.
            "&package_id=".$package_id."&paymentBrand=".$PaymentBrandId."&merchantTransactionId=".$merchantTransactionId
            ."&price=".$price."&Vat=".$Vat;
    }
    else{
        return response()->json(['status' => false, 'message' => "error,please try again",'$responseData'=>$responseData], 200);
    }
    return response()->json(['status' => true, 'message' => $ReturnedURL,'repomse'=>json_decode($responseData),"EE"=>$entityId,'$data'=>$data ], 200);
});


Auth::routes();
Route::group(['middleware' => ['localization_web'], ['as' => 'dashboard.']], function () {



    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


    Route::get('/reload-captcha', [\App\Http\Controllers\CaptchaServiceController::class, 'reloadCaptcha']);


    Route::group(['prefix' => 'admin_ltc', 'middleware' => ['auth']], function () {

        Route::get('/test', function () {
            return view("dashboard.test.index");
        })->name('home');



        Route::get('/test', [App\Http\Controllers\Dashboard\TestController::class, 'update']);
        Route::get('/send-sms', [App\Http\Controllers\Dashboard\TestController::class, 'sendSms']);


        $except = ['edit', 'create', 'show'];
        $exceptE_C = ['show'];
        Route::resource('user', App\Http\Controllers\Dashboard\UserController::class)->except($except);

        Route::resource('cities', App\Http\Controllers\Dashboard\CityController::class);
        Route::resource('clients', App\Http\Controllers\Dashboard\ClientController::class);
        Route::resource('pages', App\Http\Controllers\Dashboard\PageController::class);
        Route::resource('providers', App\Http\Controllers\Dashboard\ProviderController::class);
        Route::resource('sliders', App\Http\Controllers\Dashboard\SliderController::class)->except($except);
        Route::resource('brands', App\Http\Controllers\Dashboard\BrandController::class)->except($except);
        Route::resource('settings', App\Http\Controllers\Dashboard\SettingController::class)->except($except);
        Route::resource('users', App\Http\Controllers\Dashboard\UserController::class)->except($except);
        Route::resource('orders', App\Http\Controllers\Dashboard\OrderController::class);
        Route::resource('services', App\Http\Controllers\Dashboard\ServiceController::class)->except($except);
        Route::resource('spare-parts', App\Http\Controllers\Dashboard\SparePartController::class);
        Route::resource('survey-questions', App\Http\Controllers\Dashboard\SurveyQuestionController::class);
        Route::resource('complaints-suggestions', App\Http\Controllers\Dashboard\ComplaintSuggestionController::class);
        Route::resource('loyalty-points', App\Http\Controllers\Dashboard\LoyaltyPointController::class);
        Route::resource('prices-points', App\Http\Controllers\Dashboard\PricePointController::class);
        Route::resource('coupons', App\Http\Controllers\Dashboard\CouponController::class);

        Route::resource('roles', App\Http\Controllers\Dashboard\RoleController::class);
        Route::resource('notifications', App\Http\Controllers\Dashboard\NotificationController::class);
        Route::resource('messages', App\Http\Controllers\Dashboard\UserMessageController::class);

        Route::group(['prefix' => 'cities'], function () {
            Route::post('/update-city/{id}', [App\Http\Controllers\Dashboard\CityController::class, 'updateAxios'])->name('city.updateAxios');
        });


        Route::group(['prefix' => 'coupons'], function () {
            Route::post('/update-coupon/{id}', [App\Http\Controllers\Dashboard\CouponController::class, 'updateAxios'])->name('coupon.updateAxios');
        });

        Route::group(['prefix' => 'loyalty-points'], function () {
            Route::post('/update-loyalty-point/{id}', [App\Http\Controllers\Dashboard\LoyaltyPointController::class, 'updateAxios'])->name('loyalty-point.updateAxios');
        });

        Route::group(['prefix' => 'clients'], function () {

            Route::post('/update-client/{id}', [App\Http\Controllers\Dashboard\ClientController::class, 'updateAxios'])->name('client.updateAxios');
//            Route::get('/getClient', [App\Http\Controllers\Dashboard\ClientController::class, 'getClient'])->name('client.getClient');
            Route::post('/getClient', [App\Http\Controllers\Dashboard\ClientController::class, 'getClient'])->name('client.getClient');
            Route::post('/update-client-block/{id}', [App\Http\Controllers\Dashboard\ClientController::class, 'updateAxiosBlock'])->name('client.updateAxiosBlock');
        });


        Route::group(['prefix' => 'complaints-suggestions'], function () {
            Route::post('/replay/{id}', [App\Http\Controllers\Dashboard\ComplaintSuggestionController::class, 'replay'])->name('complaintsSuggestion.replay');
        });

        Route::group(['prefix' => 'orders'], function () {
            Route::post('/order-assign', [App\Http\Controllers\Dashboard\OrderController::class, 'assign'])->name('order.assign');
            Route::post('/order-reject', [App\Http\Controllers\Dashboard\OrderController::class, 'reject'])->name('order.reject');
            Route::post('/order-updates/{id}', [App\Http\Controllers\Dashboard\OrderController::class, 'updates'])->name('order.updates');
            Route::post('/update-collection/{id}', [App\Http\Controllers\Dashboard\OrderController::class, 'updateCollection'])->name('order.updateCollection');
            Route::post('/reject-canceled/{id}', [App\Http\Controllers\Dashboard\OrderController::class, 'rejectCanceled'])->name('order.rejectCanceled');
            Route::post('/new-cost', [App\Http\Controllers\Dashboard\OrderController::class, 'newCost'])->name('order.newCost');
            Route::post('/modification-status', [App\Http\Controllers\Dashboard\OrderController::class, 'modificationStatus'])->name('order.modification-status');
            Route::post('/modification-status-reject-admin', [App\Http\Controllers\Dashboard\OrderController::class, 'modificationStatusRejectAdmin'])->name('order.modificationStatusRejectAdmin');
        });

        Route::post('/order-getProviders', [App\Http\Controllers\Dashboard\OrderController::class, 'getProviders'])->name('order.getProviders');

        Route::get('/order-subServices', [App\Http\Controllers\Dashboard\OrderController::class, 'subServices'])->name('order.subServices');

        Route::group(['prefix' => 'providers'], function () {
            Route::post('/update-provider/{id}', [App\Http\Controllers\Dashboard\ProviderController::class, 'updateAxios'])->name('provider.updateAxios');
            Route::post('/update-city-provider/{id}', [App\Http\Controllers\Dashboard\ProviderController::class, 'updateCityAxios'])->name('provider.updateCityAxios');

            Route::post('/update-provider-block/{id}', [App\Http\Controllers\Dashboard\ProviderController::class, 'updateAxiosBlock'])->name('provider.updateAxiosBlock');
        });


        Route::group(['prefix' => 'users'], function () {

app/Models/Service.php
<?php

namespace App\Models;

use App\Traits\ActiveStatusTrait;
use Astrotomic\Translatable\Contracts\Translatable as TranslatableContract;
use Astrotomic\Translatable\Translatable;
use Illuminate\Database\Eloquent\Model;
use App\Enums\ActiveEnum;
class Service extends Model implements TranslatableContract
{
    use Translatable , ActiveStatusTrait;
    protected $guarded =['id'];
    public $translatedAttributes = ['name'];

    public function translatesItems(){
        return $this->hasMany(ServiceTranslation::class );
    }

    public function scopeParent( $query )
    {
        return $query->where("parent_id" , 0)->orWhereNull("parent_id") ;
    }

    public function scopeChildren( $query )
    {
        return $query->where("parent_id" , ">" ,0);
    }

    public function scopeChildrenItems( $query )
    {
        return $query->where("parent_id" , ">" ,0);
    }
    public function scopeActive( $query )
    {
        return $query->where("active" , ActiveEnum::ACTIVE->value);
    }

    public function getActiveStatusAttribute()
    {
        return $this->active == ActiveEnum::ACTIVE->value ? ['className' => 'success' , 'text' => 'نشط'] : ['className' => 'danger' , 'text' =>  'غير نشط'] ;
    }

    public function parentItem()
    {
        return $this->belongsTo( Service::class , "parent_id"  , "id" );
    }

    public function children()
    {
        return $this->hasMany( Service::class , "parent_id"  , "id" );
    }

    public function activeChildren()
    {
        return $this->hasMany( Service::class , "parent_id"  , "id" )
            ->where("active","active");
    }
}

app/Http/Controllers/Dashboard/BrandController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Http\Requests\Dashboard\Brand\BrandStoreRequest;
use App\Http\Requests\Dashboard\Brand\BrandUpdateRequest;
use App\Models\Brand;
use App\Services\BrandService;
use App\Traits\UploadFile;
use Illuminate\Http\Request;

class BrandController extends Controller
{
    protected $model;
    protected $viewsDomain = 'dashboard.brands.';
    use UploadFile;

    public function __construct()
    {
        $this->model = new Brand();

        $this->middleware('permission:brands-list|brands-create|brands-edit|brands-delete', ['only' => ['index', 'show']]);
        $this->middleware('permission:brands-create', ['only' => ['create', 'store']]);
        $this->middleware('permission:brands-edit', ['only' => ['edit', 'update']]);
        $this->middleware('permission:brands-delete', ['only' => ['destroy']]);

    }

    private function view($view, $params = [])
    {
        return view($this->viewsDomain . $view, $params);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request , BrandService $brandService)
    {
        $items = $brandService->index($request->all()) ;
        return $this->view('index', compact('items'));
    }

    public function store( BrandStoreRequest $request, BrandService $brandService )
    {
        $brandService->store($request->validated()) ;
        flash(__('messages.added_successfully'))->success();
        return back();
    }

    public function update( BrandUpdateRequest $request, $id , BrandService $brandService)
    {
        $brandService->update($request->validated() ,$id ) ;
        flash(__('messages.updated_successfully'))->success();
        return back();
    }

    public function destroy($id , BrandService $brandService)
    {
        $isDeleted = $brandService->delete($id);
        if ( $isDeleted ) {
            flash(__('messages.deleted_successfully'))->success();
        }else{
            flash(__('messages.cant_deleted'))->error();
        }
        return back();

    }

    public function updateAxios( Request $request , $id )
    {
        $item = $this->model->findOrFail($id);
        $data = [] ;
        foreach ( $request->all() as $key => $value )
        {
            $data = [ $key => $value ] ;
        }
        $item->update($data);
        return response()->json(["status" => true , "message" => __('messages.updated_successfully') ]) ;
    }
}

app/Http/Controllers/Dashboard/CityController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Http\Requests\Dashboard\City\CityStoreRequest;
use App\Http\Requests\Dashboard\City\LoginRequest;
use App\Http\Requests\Dashboard\City\CityUpdateRequest;
use App\Models\City;
use App\Services\CityService;
use Illuminate\Http\Request;

class CityController extends Controller
{
    protected $model;
    protected $viewsDomain = 'dashboard.cities.';

    public function __construct()
    {
        $this->model = new City();

        $this->middleware('permission:cities-list|cities-create|cities-edit|cities-delete', ['only' => ['index', 'show']]);
        $this->middleware('permission:cities-create', ['only' => ['create', 'store']]);
        $this->middleware('permission:cities-edit', ['only' => ['edit', 'update']]);
        $this->middleware('permission:cities-delete', ['only' => ['destroy']]);

    }

    private function view($view, $params = [])
    {
        return view($this->viewsDomain . $view, $params);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request , CityService $cityService)
    {
        $cities = $cityService->index($request->all()) ;
        return $this->view('index', compact('cities'));
    }


    public function store(CityStoreRequest $request, CityService $cityService )
    {
        $cityService->store($request->validated()) ;
        flash(__('messages.added_successfully'))->success();
        return back();
    }

    public function update( CityUpdateRequest $request, $id, CityService $cityService)
    {
        $cityService->update($id , $request->validated()) ;
        flash(__('messages.updated_successfully'))->success();
        return back();
    }

    public function edit( $id , CityService $cityService)
    {
        $item = $cityService->show($id) ;
        $polygonLatLng = [];

        $polygon = $item->zone_polygon;

        //POLYGON((30.811489 30.9902944,30.7923579 30.9630002,))
        if($polygon && $polygon !=null && $polygon !='' && strpos($polygon, 'POLYGON((') !== false){
            $poygonstring = str_replace("POLYGON((","",$polygon);
            $poygonstring = str_replace("))","",$poygonstring);
            $stringArrComma = explode(',', $poygonstring);
            $iObject=0;
            foreach($stringArrComma as $point){
                $point = trim($point);
                $stringArrspace = explode(' ', $point);
                if($stringArrspace && $stringArrspace!=null && count($stringArrspace)>0){
                    $polygonLatLng[$iObject]["lat"]=(float)$stringArrspace[0];
                    $polygonLatLng[$iObject]["lng"]=(float)$stringArrspace[1];
                    $iObject=$iObject +1;
                }

            }
        }
        return $this->view('edit', compact('item' ,'polygonLatLng'));
    }

    public function destroy($id , CityService $cityService)
    {
        $cityService->delete($id);
        flash(__("messages.deleted_successfully"))->success();
        return back();
    }

    public function updateAxios( Request $request , $id )
    {
        $item = $this->model->findOrFail($id);
        $data = [] ;
        foreach ( $request->all() as $key => $value )
        {
            $data = [ $key => $value ] ;
        }
        $item->update($data);
        return response()->json(["status" => true , "message" => __('messages.updated_successfully') ]) ;
    }
}

resources/views/dashboard/pages/create.blade.php
@extends('dashboard.layouts.app', ['title' => 'أضف صفحه تعريفيه'])
@section('content')
    <div class="row">
        <div class="col-lg-12 col-xl-12 stretch-card">
            <div class="card">
                <div class="card-body">
                    <form method="post" action="{{route("pages.store")}}">
                        @csrf
                        <div class="form-group row">
                            <div class="col-lg-2">
                                <label for="add_name" class="col-form-label">اسم الصفحه :</label>
                            </div>
                            <div class="col-lg-3">
                                <input type="text" class="form-control" name="name" required id="add_name">
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-lg-2">
                                <label for="name_en" class="col-form-label">اسم الصفحه - En :</label>
                            </div>
                            <div class="col-lg-3">
                                <input type="text" class="form-control" name="name_en" required id="name_en">
                            </div>
                        </div>


                        <div class="form-group row">
                            <div class="col-lg-2">
                                <label for="ordering" class="col-form-label">الترتيب :</label>
                            </div>
                            <div class="col-lg-3">
                                <input type="number" class="form-control" name="ordering" required id="ordering">
                            </div>
                        </div>



                        <div class="form-group row">
                            <div class="col-lg-2">
                                <label for="description" class="col-form-label">محتوي الصفحه :</label>
                            </div>
                            <div class="col-lg-10">
                                <textarea class="form-control tinymceExample" id="description" rows="6" name="description"></textarea>
                            </div>
                        </div>




                        <div class="form-group row">
                            <div class="col-lg-2">
                                <label for="add_page" class="col-form-label">محتوي الصفحه En :</label>
                            </div>
                            <div class="col-lg-10">
                                <textarea class="form-control tinymceExample" rows="6" name="description_en"></textarea>
                            </div>
                        </div>



                        <div class="form-group row">
                            <div class="col-lg-2">
                                <label for="add_active" class="col-form-label">  حاله الظهور :</label>
                            </div>
                            <div class="col-lg-10">
                                <input type="hidden" name="active" value="inactive">
                                <label class="switch">
                                    <input type="checkbox" name="active" value="active">
                                    <span class="slider round"></span>
                                </label>
                            </div>
                        </div>


                        <div class="form-group row">
                            <div class="col-md-6 offset-md-3">
                                <button type="submit" class="btn btn-primary"> حفظ </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script src="{{ asset('/') }}assets/vendors/tinymce/tinymce.min.js"></script>
    <script src="{{ asset('/') }}assets/js/tinymce.js"></script>
    <script>
        if ($(".tinymceExample").length) {
            tinymce.init({
                selector: '.tinymceExample',
                height: 300,
                theme: 'silver',
                plugins: [
                    'advlist autolink lists link image charmap print preview hr anchor pagebreak',
                    'searchreplace wordcount visualblocks visualchars code fullscreen',
                ],
                toolbar1: 'undo redo | insert | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
                toolbar2: 'print preview media | forecolor backcolor emoticons | codesample help',
                image_advtab: true,
                templates: [{
                    title: 'Test template 1',
                    content: 'Test 1'
                },
                    {
                        title: 'Test template 2',
                        content: 'Test 2'
                    }
                ],
                content_css: []
            });
        }
    </script>

@endpush

resources/views/dashboard/pages/index.blade.php
@extends('dashboard.layouts.app', ['title' => __('app.titles.pages')])
@section('content')
    {{--@push('button')--}}
        {{--@can("notifications-create")--}}
        {{--<div class="d-flex align-items-center flex-wrap text-nowrap">--}}
            {{--<a href="{{route("pages.create")}}" class="btn btn-primary" >--}}
                {{--{{__('app.pages.add')}}--}}
            {{--</a>--}}
        {{--</div>--}}
        {{--@endcan--}}
    {{--@endpush--}}
    <div class="row">
        <div class="col-lg-12 col-xl-12 stretch-card">
            <div class="card mb-3">
                <div class="card-body filter">
                    <form class="filter_form">
                        <div class="form-group row">
                            <label for="place" class="col-sm-2 col-form-label"> {{__('app.pages.name')}} </label>
                            <div class="col-sm-3">
                                <input type="text" class="form-control" name="name" value="{{ request('name') }}"/>
                            </div>
                            <div class="col-sm-2">
                                <button type="submit" class="btn btn-primary submit"> {{__('app.search')}} </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-lg-12 col-xl-12 stretch-card">
            <div class="card">
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-hover mb-0">
                            <thead>
                            <tr>
                                <th class="pt-0">#</th>
                                <th class="pt-0"> {{__('app.pages.page_title')}} </th>
                                {{--<th class="pt-0"> {{__('app.name_en')}} </th>--}}
                                {{--<th class="pt-0"> {{__('app.status')}} </th>--}}
                                {{--<th class="pt-0"> {{__('app.ordering')}} </th>--}}
                                <th class="pt-0"> {{__('app.processes')}} </th>
                            </tr>
                            </thead>
                            <tbody>
                            @forelse($items as $item )
                                <tr>
                                    <td>{{ $loop->iteration }}</td>
                                    <td> {{optional( $item->translate('ar') )->name }} </td>
                                    {{--<td> {{ optional( $item->translate('en') )->name  }} </td>--}}

                                    {{--<td>--}}
                                        {{--<span class="badge badge-lg badge-{{$item->active_status['className']}}">--}}
                                            {{--{{$item->active_status['text']}}--}}
                                        {{--</span>--}}
                                    {{--</td>--}}
                                    {{--<td> {{ $item->ordering  }} </td>--}}
                                    <td>
                                        @can("pages-edit")
                                        <a href="{{route("pages.edit", $item->id)}}" data-id="{{$item->id}}"
                                           class="btn btn-primary btn-icon aligner ">
                                            <i data-feather="edit"></i>
                                        </a>
                                        @endcan
                                        {{--@can("pages-delete")--}}
                                        {{--<button type="submit" class="btn btn-danger btn-icon aligner"--}}
                                                {{--onclick="showSwal('passing-parameter-execute-cancel' , '{{route("pages.destroy", $item->id)}}' )" >--}}
                                            {{--<i data-feather="trash"></i>--}}
                                        {{--</button>--}}
                                        {{--@endcan--}}
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="7" class="danger text-center">{{__('app.no_data')}}</td>
                                </tr>
                            @endforelse
                            </tbody>
                        </table>
                        <div class="text-center">
                            {!! $items->appends(request()->query())->render() !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('scripts')
@endpush