routes/web.php
        \Log::error('Email sending failed: ' . $e->getMessage());
        dd(">>",$e->getMessage()) ;
    }
    return $res;
});

Route::get('/send-email-121', function () {

    return Mail::raw('This is a test email', function($message) {
        $message->to('mahmoud.ragaey.99@gmail.com');
        $message->subject('Test Email');
    });

    return $tt ;

//$to = "melzaiady@yahoo.co.uk";
//$to = "mahmoud.ragaey.99@gmail.com";
//$subject = "HTML email";
//
//$message = "
//<html>
//<head>
//<title>HTML email</title>
//</head>
//<body>
//<p>This email contains HTML Tags!</p>
//<table>
//<tr>
//<th>Firstname</th>
//<th>Lastname</th>
//</tr>
//<tr>
//<td>John</td>
//<td>Doe</td>
//</tr>
//</table>
//</body>
//</html>
//";

// Always set content-type when sending HTML email
//$headers = "MIME-Version: 1.0" . "\r\n";
//$headers .= "Content-type:text/html;charset=UTF-8" . "\r\n";
//
//// More headers
//$headers .= 'From: <info@mragaey.com>' . "\r\n";
//
//mail($to,$subject,$message,$headers);

    return "Done"  ;
});

Route::get('/send-email-21', function () {
    $email = "mahmoud.ragaey.99@gmail.com" ;
    $subject ="subject" ;
    $text = "text" ;
    $phone = "090090909" ;
    $data = array('email' => $email, 'subject' => $subject, 'body' => $text, 'mobile'=>$phone);

    //********* end send email
    $aa = Mail::send('emails_items.contact', $data, function($message) use ($data) {
        $message->from($data['email']);
        $message->to('mahmoud.ragaey.99@gmail.com');
        $message->subject($data['subject']);
    });

    return $aa ;



    $em = "mahmoud.ragaey.99@gmail.com" ;
    $name  = " name" ;
    return \Illuminate\Support\Facades\Mail::to($em)->send(new \App\Mail\ContactEmail($em , $name));

    return "sasa";

    $toAdminMail= "your_admin_email@gmail.com";
    $message  = " Check Contact Form" ;


    \Illuminate\Support\Facades\Mail::to($toAdminMail)->send(new \App\Notifications\ContactMessage($message , $name));

    return "DONE" ;


    $provider = \App\Models\Client::where("id" ,54)->first();
    $name ="Yaaarb" ;
    $order_id =11 ;
    $message = 'new request been sent to you and awaiting your approval of the request :: ' .$name .' :: order id ::'.$order_id;
    $titleNote =  'app.note_new_request' ;
    $provider->notify(new \App\Notifications\ClientNotification($message , $titleNote));
    return "Done" ;
});

Route::get('/hyperPaypayment-23', function () {
    $id = "B5EAB7D8FD0D9BEEDC738820C043833A.uat01-vm-tx01" ;

    $url = "https://test.oppwa.com/v1/checkouts/".$id."/payment?entityId=8a8294174d0595bb014d05d82e5b01d2";
//    $url .= "";

    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_HTTPHEADER, array(
        'Authorization:Bearer OGE4Mjk0MTc0ZDA1OTViYjAxNGQwNWQ4MjllNzAxZDF8OVRuSlBjMm45aA=='));
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);// this should be set to true in production
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    $responseData = curl_exec($ch);
    if(curl_errno($ch)) {
        return curl_error($ch);
    }
    curl_close($ch);
    return $responseData;
});

Route::get('/hyperPaypayment-22', function () {

    //visa 8ac7a4c78694e687018697314f3e02f4
    // 8ac7a4c78694e68701869731bae102f9

//    return config("settings.payments.visaEntityID") ;

    $price = 92.00;

    $url = config('settings.payments.url')."/checkouts";
    $data = "entityId=".config('settings.payments.visaEntityID')."" .
        "&amount=".$price.
        "&currency=".config('settings.payments.currency')."".
        "&paymentType=DB";

    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_HTTPHEADER, array(
        'Authorization:Bearer OGE4Mjk0MTc0ZDA1OTViYjAxNGQwNWQ4MjllNzAxZDF8OVRuSlBjMm45aA=='));
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false); // this should be set to true in production
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    $responseData = curl_exec($ch);

    if(curl_errno($ch)) {
        return curl_error($ch);
    }
    curl_close($ch);

    return  json_decode($responseData);

    return $responseData;

});


Route::get('/hyperPaypayment-21', function () {
    $user = \App\Models\Client::first();

    $price = 200;
    $amount = $price;// $request->amount ;
    //
    $package_id = 2 ;
    $merchantTransactionId = $user->id.strtotime(date("Y-m-d H:m:s"));
    $userID = $user->id;
    //
    $UserName= $user->name;
    $email = $user->email;
    $street1= "street address of customer";
    $city= "SA";
    $state= "state";
    $country= "SA";
    $postcode="12345";
    $customerGivenName=$user->first_name;
    $customerSurName=$user->first_name.$user->mobile;
    $PaymentBrandId = 3 ;
    if($PaymentBrandId == 0 || $PaymentBrandId == 2){ // visa , stc
        $entityId=config('constants.Payment.VisaEntityID'); //test -- VisaEntityID
        $entityId="8ac7a4c78694e687018697314f3e02f4"; //test -- VisaEntityID
    }
    else if($PaymentBrandId == 1){ //mada
        $entityId=config('constants.Payment.MadaEntityID'); //test -- MadaEntityID
        $entityId="8ac7a4c78694e68701869731bae102f9"; //test -- MadaEntityID
    }
    else if($PaymentBrandId == 3){ //  apple pay
        $entityId=config('constants.Payment.ApplePayEntityID'); //test -- apple pay   "8ac7a4c87edd1a80017ede0f92940431";//
    }
    $url = "https://oppwa.com/v1/checkouts";
    //$url = "https://test.oppwa.com/v1/checkouts"; //test
    $data = "entityId=".$entityId.
        "&amount=". $amount .
        "&currency=SAR&paymentType=DB&merchantTransactionId=".$merchantTransactionId.
        "&customer.email=".$email."&billing.street1=".$street1."&billing.city=".$city."&billing.state=".$state.
        "&billing.country=".$country."&billing.postcode=".$postcode;
    if($PaymentBrandId != 2 && $PaymentBrandId != 3){
        $data .="&createRegistration=true";
    }
    if($PaymentBrandId == 3){
        $data = "entityId=".$entityId.
            "&amount=". $amount .
            "&currency=SAR&paymentType=DB&merchantTransactionId=".$merchantTransactionId.
            "&customer.email=".$email."&billing.street1=".$street1."&billing.city=".$city."&billing.state=".$state.
            "&billing.country=".$country."&billing.postcode=".$postcode;
    }


    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_HTTPHEADER, array(
        'Authorization:Bearer OGFjZGE0Y2U3YTgxMzUwOTAxN2E4MTY2MzM3MjAxZDR8ejkzOEdFN2o1Tg=='));
    // curl_setopt($ch, CURLOPT_HTTPHEADER, array(
    //     'Authorization:Bearer OGFjN2E0Yzc3NjQxYjEzMDAxNzY0MjliMDkyODA1ZmJ8SFl3NlB3V3pzSw=='));
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    $responseData = curl_exec($ch);


    if(curl_errno($ch)) {
        return response()->json(['status' => false, 'message' => __('Please try again'),'$responseData'=>$responseData], 200);
    }
    curl_close($ch);
    $Vat = 14;
    $checkoutId = json_decode($responseData);

    return $checkoutId ;
    if($checkoutId->result->code == "000.200.100"){
        $checkoutId = $checkoutId->id;
        $ReturnedURL = config('global.WebsiteURL')."public/en/hyperpay?checkoutId=".$checkoutId."&user_id=".$userID.
            "&package_id=".$package_id."&paymentBrand=".$PaymentBrandId."&merchantTransactionId=".$merchantTransactionId
            ."&price=".$price."&Vat=".$Vat;
    }
    else{
        return response()->json(['status' => false, 'message' => "error,please try again",'$responseData'=>$responseData], 200);
    }
    return response()->json(['status' => true, 'message' => $ReturnedURL,'repomse'=>json_decode($responseData),"EE"=>$entityId,'$data'=>$data ], 200);
});


Auth::routes();
Route::group(['middleware' => ['localization_web'], ['as' => 'dashboard.']], function () {



    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


    Route::get('/reload-captcha', [\App\Http\Controllers\CaptchaServiceController::class, 'reloadCaptcha']);


    Route::group(['prefix' => 'admin_ltc', 'middleware' => ['auth']], function () {

        Route::get('/test', function () {
            return view("dashboard.test.index");
        })->name('home');



        Route::get('/test', [App\Http\Controllers\Dashboard\TestController::class, 'update']);
        Route::get('/send-sms', [App\Http\Controllers\Dashboard\TestController::class, 'sendSms']);


        $except = ['edit', 'create', 'show'];
        $exceptE_C = ['show'];
        Route::resource('user', App\Http\Controllers\Dashboard\UserController::class)->except($except);

        Route::resource('cities', App\Http\Controllers\Dashboard\CityController::class);
        Route::resource('clients', App\Http\Controllers\Dashboard\ClientController::class);
        Route::resource('pages', App\Http\Controllers\Dashboard\PageController::class);
        Route::resource('providers', App\Http\Controllers\Dashboard\ProviderController::class);
        Route::resource('sliders', App\Http\Controllers\Dashboard\SliderController::class)->except($except);
        Route::resource('brands', App\Http\Controllers\Dashboard\BrandController::class)->except($except);
        Route::resource('settings', App\Http\Controllers\Dashboard\SettingController::class)->except($except);
        Route::resource('users', App\Http\Controllers\Dashboard\UserController::class)->except($except);
        Route::resource('orders', App\Http\Controllers\Dashboard\OrderController::class);
        Route::resource('services', App\Http\Controllers\Dashboard\ServiceController::class)->except($except);
        Route::resource('spare-parts', App\Http\Controllers\Dashboard\SparePartController::class);

app/Models/Setting.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Setting extends Model
{
    use HasFactory;
    protected $guarded = ['id'] ;
}

app/Http/Controllers/Api/SettingController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Requests\Api\SendEmailRequest;
use App\Http\Resources\SettingsResource;
use App\Mail\ContactEmail;
use App\Models\Setting;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Request;

class SettingController extends BaseController
{
    public function index()
    {
        $settings = Setting::first() ;
        $settings =  new SettingsResource($settings) ;
        return $this->sendResponse($settings, __("messages.successfully"));
    }

    public function sendEmail( SendEmailRequest $request )
    {

        $user = Request::user() ;
        $name = $user->full_name ;
        $message = $request->message ;
        $settings = Setting::first();
        Mail::to($settings->email)->send(new ContactEmail($message , $name));
        return $this->sendResponse("", __("messages.massege_send_successfully"));
    }
}

app/Http/Controllers/Dashboard/BrandController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Http\Requests\Dashboard\Brand\BrandStoreRequest;
use App\Http\Requests\Dashboard\Brand\BrandUpdateRequest;
use App\Models\Brand;
use App\Services\BrandService;
use App\Traits\UploadFile;
use Illuminate\Http\Request;

class BrandController extends Controller
{
    protected $model;
    protected $viewsDomain = 'dashboard.brands.';
    use UploadFile;

    public function __construct()
    {
        $this->model = new Brand();

        $this->middleware('permission:brands-list|brands-create|brands-edit|brands-delete', ['only' => ['index', 'show']]);
        $this->middleware('permission:brands-create', ['only' => ['create', 'store']]);
        $this->middleware('permission:brands-edit', ['only' => ['edit', 'update']]);
        $this->middleware('permission:brands-delete', ['only' => ['destroy']]);

    }

    private function view($view, $params = [])
    {
        return view($this->viewsDomain . $view, $params);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request , BrandService $brandService)
    {
        $items = $brandService->index($request->all()) ;
        return $this->view('index', compact('items'));
    }

    public function store( BrandStoreRequest $request, BrandService $brandService )
    {
        $brandService->store($request->validated()) ;
        flash(__('messages.added_successfully'))->success();
        return back();
    }

    public function update( BrandUpdateRequest $request, $id , BrandService $brandService)
    {
        $brandService->update($request->validated() ,$id ) ;
        flash(__('messages.updated_successfully'))->success();
        return back();
    }

    public function destroy($id , BrandService $brandService)
    {
        $isDeleted = $brandService->delete($id);
        if ( $isDeleted ) {
            flash(__('messages.deleted_successfully'))->success();
        }else{
            flash(__('messages.cant_deleted'))->error();
        }
        return back();

    }

    public function updateAxios( Request $request , $id )
    {
        $item = $this->model->findOrFail($id);
        $data = [] ;
        foreach ( $request->all() as $key => $value )
        {
            $data = [ $key => $value ] ;
        }
        $item->update($data);
        return response()->json(["status" => true , "message" => __('messages.updated_successfully') ]) ;
    }
}

app/Http/Controllers/Dashboard/CityController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Http\Requests\Dashboard\City\CityStoreRequest;
use App\Http\Requests\Dashboard\City\LoginRequest;
use App\Http\Requests\Dashboard\City\CityUpdateRequest;
use App\Models\City;
use App\Services\CityService;
use Illuminate\Http\Request;

class CityController extends Controller
{
    protected $model;
    protected $viewsDomain = 'dashboard.cities.';

    public function __construct()
    {
        $this->model = new City();

        $this->middleware('permission:cities-list|cities-create|cities-edit|cities-delete', ['only' => ['index', 'show']]);
        $this->middleware('permission:cities-create', ['only' => ['create', 'store']]);
        $this->middleware('permission:cities-edit', ['only' => ['edit', 'update']]);
        $this->middleware('permission:cities-delete', ['only' => ['destroy']]);

    }

    private function view($view, $params = [])
    {
        return view($this->viewsDomain . $view, $params);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request , CityService $cityService)
    {
        $cities = $cityService->index($request->all()) ;
        return $this->view('index', compact('cities'));
    }


    public function store(CityStoreRequest $request, CityService $cityService )
    {
        $cityService->store($request->validated()) ;
        flash(__('messages.added_successfully'))->success();
        return back();
    }

    public function update( CityUpdateRequest $request, $id, CityService $cityService)
    {
        $cityService->update($id , $request->validated()) ;
        flash(__('messages.updated_successfully'))->success();
        return back();
    }

    public function edit( $id , CityService $cityService)
    {
        $item = $cityService->show($id) ;
        $polygonLatLng = [];

        $polygon = $item->zone_polygon;

        //POLYGON((30.811489 30.9902944,30.7923579 30.9630002,))
        if($polygon && $polygon !=null && $polygon !='' && strpos($polygon, 'POLYGON((') !== false){
            $poygonstring = str_replace("POLYGON((","",$polygon);
            $poygonstring = str_replace("))","",$poygonstring);
            $stringArrComma = explode(',', $poygonstring);
            $iObject=0;
            foreach($stringArrComma as $point){
                $point = trim($point);
                $stringArrspace = explode(' ', $point);
                if($stringArrspace && $stringArrspace!=null && count($stringArrspace)>0){
                    $polygonLatLng[$iObject]["lat"]=(float)$stringArrspace[0];
                    $polygonLatLng[$iObject]["lng"]=(float)$stringArrspace[1];
                    $iObject=$iObject +1;
                }

            }
        }
        return $this->view('edit', compact('item' ,'polygonLatLng'));
    }

    public function destroy($id , CityService $cityService)
    {
        $cityService->delete($id);
        flash(__("messages.deleted_successfully"))->success();
        return back();
    }

    public function updateAxios( Request $request , $id )
    {
        $item = $this->model->findOrFail($id);
        $data = [] ;
        foreach ( $request->all() as $key => $value )
        {
            $data = [ $key => $value ] ;
        }
        $item->update($data);
        return response()->json(["status" => true , "message" => __('messages.updated_successfully') ]) ;
    }
}

resources/views/dashboard/settings/index.blade.php
@extends('dashboard.layouts.app', ['title' => __('app.titles.settings')])
@section('content')
    <div class="row">
        <div class="col-lg-12 col-xl-12 stretch-card">
            <div class="card">
                <div class="card-body">
                    <form method="post" id="add-form" action="{{route("settings.store")}}">
                        @csrf

                        <div class="form-group row">
                            <div class="col-lg-2">
                                <label for="add_name" class="col-form-label">{{__('app.settings.visit')}} :</label>
                            </div>
                            <div class="col-lg-4">
                                <input type="number" min="1" value="{{$setting->visit}}" class="form-control" name="visit" id="add_name">
                            </div>

                        </div>

                        <hr>
                        <div class="form-group row">
                            <div class="col-lg-2">
                                <label for="add_name" class="col-form-label">{{__('app.settings.site_name')}} :</label>
                            </div>
                            <div class="col-lg-4">
                                <input type="text" value="{{$setting->site_name}}" class="form-control" name="site_name" id="add_name">
                            </div>

                            <div class="col-lg-2">
                                <label for="add_email" class="col-form-label"> {{__('app.email')}} :</label>
                            </div>
                            <div class="col-lg-4">
                                <input type="email" class="form-control" name="email" value="{{$setting->email}}" id="add_email">
                            </div>
                        </div>


                        <div class="form-group row">
                            <div class="col-lg-2">
                                <label for="add_phone" class="col-form-label">{{__('app.phone')}}  :</label>
                            </div>
                            <div class="col-lg-4">
                                <input type="text" class="form-control" name="phone" value="{{$setting->phone}}" id="add_phone">
                            </div>

                            <div class="col-lg-2">
                                <label for="add_phone2" class="col-form-label">{{__('app.phone')}}  :</label>
                            </div>
                            <div class="col-lg-4">
                                <input type="text" class="form-control" name="phone2" value="{{$setting->phone2}}" id="add_phone2">
                            </div>
                        </div>


                        <div class="form-group row mb-3">
                            <div class="col-lg-2">
                                <label for="meta_description" class="col-form-label"> {{__('app.settings.meta_description')}} :</label>
                            </div>
                            <div class="col-lg-10">
                                <textarea class="form-control" name="meta_description" rows="7" >{{$setting->meta_description}}</textarea>
                            </div>
                        </div>
                        <div class="form-group row mb-3">
                            <div class="col-lg-2">
                                <label for="meta_keywords" class="col-form-label">{{__('app.settings.meta_keywords')}} :</label>
                            </div>
                            <div class="col-lg-10">
                                <textarea class="form-control" name="meta_keywords" rows="7" >{{$setting->meta_keywords}}</textarea>
                            </div>
                        </div>
                        <hr>

                        <div class="form-group row">
                            <div class="col-lg-2">
                                <label for="add_facebook" class="col-form-label">{{__('app.facebook')}}  :</label>
                            </div>
                            <div class="col-lg-4">
                                <input type="text" class="form-control" name="facebook" value="{{$setting->facebook}}" id="add_facebook">
                            </div>

                            <div class="col-lg-2">
                                <label for="add_twitter" class="col-form-label">{{__('app.twitter')}}  :</label>
                            </div>
                            <div class="col-lg-4">
                                <input type="text" class="form-control" name="twitter" value="{{$setting->twitter}}" id="add_twitter">
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-lg-2">
                                <label for="add_linkedin" class="col-form-label">{{__('app.linkedin')}}  :</label>
                            </div>
                            <div class="col-lg-4">
                                <input type="text" class="form-control" name="linkedin" value="{{$setting->linkedin}}" id="add_linkedin">
                            </div>

                            <div class="col-lg-2">
                                <label for="add_instagram" class="col-form-label">{{__('app.instagram')}}  :</label>
                            </div>
                            <div class="col-lg-4">
                                <input type="text" class="form-control" name="instagram" value="{{$setting->instagram}}" id="add_instagram">
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-md-6 offset-md-2">
                                <button type="submit" class="btn btn-primary"> {{__('app.save')}} </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>


@endsection

@push('scripts')
    @include('dashboard.settings.script')
@endpush

resources/views/dashboard/settings/script.blade.php
<script>
    $("#add-form").validate({
        rules: {
            site_name: {
                required: true,
            },
            email :{
                required: true,
            },

            phone :{
                required: true,
            },
            phone2 :{
                required: true,
            },

            facebook :{
                url: true
            },
            twitter :{
                url: true
            },
            linkedin :{
                url: true
            },
            instagram :{
                url: true
            },
            action: "required"
        },
        messages: {
            site_name: {
                required: "{{__('app.validation.field_site_name_required')}}"
            },
            email: {
                required: "{{__('app.validation.field_email_required')}}"
            },

            phone: {
                required: "{{__('app.validation.field_phone_required')}}"
            },
            phone2 :{
                required: "{{__('app.validation.field_phone2_required')}}"
            },

            facebook :{
                url: "{{__('app.validation.field_url_required')}}"
            },
            twitter :{
                url: "{{__('app.validation.field_url_required')}}"
            },
            linkedin :{
                url: "{{__('app.validation.field_url_required')}}"
            },
            instagram :{
                url: "{{__('app.validation.field_url_required')}}"
            },




            action: "Please provide some data"
        }
    });
</script>