routes/web.php
    $state= "state";
    $country= "SA";
    $postcode="12345";
    $customerGivenName=$user->first_name;
    $customerSurName=$user->first_name.$user->mobile;
    $PaymentBrandId = 3 ;
    if($PaymentBrandId == 0 || $PaymentBrandId == 2){ // visa , stc
        $entityId=config('constants.Payment.VisaEntityID'); //test -- VisaEntityID
        $entityId="8ac7a4c78694e687018697314f3e02f4"; //test -- VisaEntityID
    }
    else if($PaymentBrandId == 1){ //mada
        $entityId=config('constants.Payment.MadaEntityID'); //test -- MadaEntityID
        $entityId="8ac7a4c78694e68701869731bae102f9"; //test -- MadaEntityID
    }
    else if($PaymentBrandId == 3){ //  apple pay
        $entityId=config('constants.Payment.ApplePayEntityID'); //test -- apple pay   "8ac7a4c87edd1a80017ede0f92940431";//
    }
    $url = "https://oppwa.com/v1/checkouts";
    //$url = "https://test.oppwa.com/v1/checkouts"; //test
    $data = "entityId=".$entityId.
        "&amount=". $amount .
        "&currency=SAR&paymentType=DB&merchantTransactionId=".$merchantTransactionId.
        "&customer.email=".$email."&billing.street1=".$street1."&billing.city=".$city."&billing.state=".$state.
        "&billing.country=".$country."&billing.postcode=".$postcode;
    if($PaymentBrandId != 2 && $PaymentBrandId != 3){
        $data .="&createRegistration=true";
    }
    if($PaymentBrandId == 3){
        $data = "entityId=".$entityId.
            "&amount=". $amount .
            "&currency=SAR&paymentType=DB&merchantTransactionId=".$merchantTransactionId.
            "&customer.email=".$email."&billing.street1=".$street1."&billing.city=".$city."&billing.state=".$state.
            "&billing.country=".$country."&billing.postcode=".$postcode;
    }


    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_HTTPHEADER, array(
        'Authorization:Bearer OGFjZGE0Y2U3YTgxMzUwOTAxN2E4MTY2MzM3MjAxZDR8ejkzOEdFN2o1Tg=='));
    // curl_setopt($ch, CURLOPT_HTTPHEADER, array(
    //     'Authorization:Bearer OGFjN2E0Yzc3NjQxYjEzMDAxNzY0MjliMDkyODA1ZmJ8SFl3NlB3V3pzSw=='));
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    $responseData = curl_exec($ch);


    if(curl_errno($ch)) {
        return response()->json(['status' => false, 'message' => __('Please try again'),'$responseData'=>$responseData], 200);
    }
    curl_close($ch);
    $Vat = 14;
    $checkoutId = json_decode($responseData);

    return $checkoutId ;
    if($checkoutId->result->code == "000.200.100"){
        $checkoutId = $checkoutId->id;
        $ReturnedURL = config('global.WebsiteURL')."public/en/hyperpay?checkoutId=".$checkoutId."&user_id=".$userID.
            "&package_id=".$package_id."&paymentBrand=".$PaymentBrandId."&merchantTransactionId=".$merchantTransactionId
            ."&price=".$price."&Vat=".$Vat;
    }
    else{
        return response()->json(['status' => false, 'message' => "error,please try again",'$responseData'=>$responseData], 200);
    }
    return response()->json(['status' => true, 'message' => $ReturnedURL,'repomse'=>json_decode($responseData),"EE"=>$entityId,'$data'=>$data ], 200);
});


Auth::routes();
Route::group(['middleware' => ['localization_web'], ['as' => 'dashboard.']], function () {



    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


    Route::get('/reload-captcha', [\App\Http\Controllers\CaptchaServiceController::class, 'reloadCaptcha']);


    Route::group(['prefix' => 'admin_ltc', 'middleware' => ['auth']], function () {

        Route::get('/test', function () {
            return view("dashboard.test.index");
        })->name('home');



        Route::get('/test', [App\Http\Controllers\Dashboard\TestController::class, 'update']);
        Route::get('/send-sms', [App\Http\Controllers\Dashboard\TestController::class, 'sendSms']);


        $except = ['edit', 'create', 'show'];
        $exceptE_C = ['show'];
        Route::resource('user', App\Http\Controllers\Dashboard\UserController::class)->except($except);

        Route::resource('cities', App\Http\Controllers\Dashboard\CityController::class);
        Route::resource('clients', App\Http\Controllers\Dashboard\ClientController::class);
        Route::resource('pages', App\Http\Controllers\Dashboard\PageController::class);
        Route::resource('providers', App\Http\Controllers\Dashboard\ProviderController::class);
        Route::resource('sliders', App\Http\Controllers\Dashboard\SliderController::class)->except($except);
        Route::resource('brands', App\Http\Controllers\Dashboard\BrandController::class)->except($except);
        Route::resource('settings', App\Http\Controllers\Dashboard\SettingController::class)->except($except);
        Route::resource('users', App\Http\Controllers\Dashboard\UserController::class)->except($except);
        Route::resource('orders', App\Http\Controllers\Dashboard\OrderController::class);
        Route::resource('services', App\Http\Controllers\Dashboard\ServiceController::class)->except($except);
        Route::resource('spare-parts', App\Http\Controllers\Dashboard\SparePartController::class);
        Route::resource('survey-questions', App\Http\Controllers\Dashboard\SurveyQuestionController::class);
        Route::resource('complaints-suggestions', App\Http\Controllers\Dashboard\ComplaintSuggestionController::class);
        Route::resource('loyalty-points', App\Http\Controllers\Dashboard\LoyaltyPointController::class);
        Route::resource('prices-points', App\Http\Controllers\Dashboard\PricePointController::class);
        Route::resource('coupons', App\Http\Controllers\Dashboard\CouponController::class);

        Route::resource('roles', App\Http\Controllers\Dashboard\RoleController::class);
        Route::resource('notifications', App\Http\Controllers\Dashboard\NotificationController::class);
        Route::resource('messages', App\Http\Controllers\Dashboard\UserMessageController::class);

        Route::group(['prefix' => 'cities'], function () {
            Route::post('/update-city/{id}', [App\Http\Controllers\Dashboard\CityController::class, 'updateAxios'])->name('city.updateAxios');
        });


        Route::group(['prefix' => 'coupons'], function () {
            Route::post('/update-coupon/{id}', [App\Http\Controllers\Dashboard\CouponController::class, 'updateAxios'])->name('coupon.updateAxios');
        });

        Route::group(['prefix' => 'loyalty-points'], function () {
            Route::post('/update-loyalty-point/{id}', [App\Http\Controllers\Dashboard\LoyaltyPointController::class, 'updateAxios'])->name('loyalty-point.updateAxios');
        });

        Route::group(['prefix' => 'clients'], function () {

            Route::post('/update-client/{id}', [App\Http\Controllers\Dashboard\ClientController::class, 'updateAxios'])->name('client.updateAxios');
//            Route::get('/getClient', [App\Http\Controllers\Dashboard\ClientController::class, 'getClient'])->name('client.getClient');
            Route::post('/getClient', [App\Http\Controllers\Dashboard\ClientController::class, 'getClient'])->name('client.getClient');
            Route::post('/update-client-block/{id}', [App\Http\Controllers\Dashboard\ClientController::class, 'updateAxiosBlock'])->name('client.updateAxiosBlock');
        });


        Route::group(['prefix' => 'complaints-suggestions'], function () {
            Route::post('/replay/{id}', [App\Http\Controllers\Dashboard\ComplaintSuggestionController::class, 'replay'])->name('complaintsSuggestion.replay');
        });

        Route::group(['prefix' => 'orders'], function () {
            Route::post('/order-assign', [App\Http\Controllers\Dashboard\OrderController::class, 'assign'])->name('order.assign');
            Route::post('/order-reject', [App\Http\Controllers\Dashboard\OrderController::class, 'reject'])->name('order.reject');
            Route::post('/order-updates/{id}', [App\Http\Controllers\Dashboard\OrderController::class, 'updates'])->name('order.updates');
            Route::post('/update-collection/{id}', [App\Http\Controllers\Dashboard\OrderController::class, 'updateCollection'])->name('order.updateCollection');
            Route::post('/reject-canceled/{id}', [App\Http\Controllers\Dashboard\OrderController::class, 'rejectCanceled'])->name('order.rejectCanceled');
            Route::post('/new-cost', [App\Http\Controllers\Dashboard\OrderController::class, 'newCost'])->name('order.newCost');
            Route::post('/modification-status', [App\Http\Controllers\Dashboard\OrderController::class, 'modificationStatus'])->name('order.modification-status');
            Route::post('/modification-status-reject-admin', [App\Http\Controllers\Dashboard\OrderController::class, 'modificationStatusRejectAdmin'])->name('order.modificationStatusRejectAdmin');
        });

        Route::post('/order-getProviders', [App\Http\Controllers\Dashboard\OrderController::class, 'getProviders'])->name('order.getProviders');

        Route::get('/order-subServices', [App\Http\Controllers\Dashboard\OrderController::class, 'subServices'])->name('order.subServices');

        Route::group(['prefix' => 'providers'], function () {
            Route::post('/update-provider/{id}', [App\Http\Controllers\Dashboard\ProviderController::class, 'updateAxios'])->name('provider.updateAxios');
            Route::post('/update-city-provider/{id}', [App\Http\Controllers\Dashboard\ProviderController::class, 'updateCityAxios'])->name('provider.updateCityAxios');

            Route::post('/update-provider-block/{id}', [App\Http\Controllers\Dashboard\ProviderController::class, 'updateAxiosBlock'])->name('provider.updateAxiosBlock');
        });


        Route::group(['prefix' => 'users'], function () {

app/Models/Client.php
<?php

namespace App\Models;

use App\Traits\ActiveStatusTrait;
use Illuminate\Database\Eloquent\Factories\HasFactory;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\Builder;


use App\Enums\ClientTypeEnum;
use Laravel\Sanctum\HasApiTokens;

class Client extends Authenticatable
{
    use HasFactory , HasApiTokens, Notifiable ,SoftDeletes, ActiveStatusTrait;

    protected $guarded = ['id'] ;

    public function scopeProvider($query)
    {
        return $query->where('type', ClientTypeEnum::PROVIDER->value );
    }

    public function scopeClient($query)
    {
        return $query->where('type', ClientTypeEnum::CLIENT->value );
    }

    public function getFullNameAttribute()
    {
        return $this->first_name ." ". $this->last_name ;
    }

    public function getAvatarImageAttribute()
    {
        if ( $this->avatar ){
            return asset($this->avatar );
        }
        return  "/kafo-development/assets/images/logo-sm.png" ;
    }

    public function getClientRateAvgAttribute()
    {
        return $this->providerOrders()->avg('client_rate');
    }

    public function clientOrders(){
        return $this->hasMany(Order::class , "client_id" ) ;
    }

    public function providerOrders(){
        return $this->hasMany(Order::class , "provider_id" ) ;
    }

    public function getProviderHoursOrdersAttribute(){
        $completionTimes = [];
        foreach ( $this->providerOrders()->get() as $key => $item ) {
            $completionTimes[] = $item->completion_time ;
        }
        return array_sum($completionTimes) ;
    }

    public function setPhoneAttribute($value){
        $this->attributes['phone'] = str_replace(' ', '', $value);
    }

    public function scopeFilter(Builder $query, $filter)
    {
        $filter->filter($query);
    }


    public function city()
    {
        return $this->belongsTo(City::class) ;
    }
}

app/Http/Controllers/Dashboard/BrandController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Http\Requests\Dashboard\Brand\BrandStoreRequest;
use App\Http\Requests\Dashboard\Brand\BrandUpdateRequest;
use App\Models\Brand;
use App\Services\BrandService;
use App\Traits\UploadFile;
use Illuminate\Http\Request;

class BrandController extends Controller
{
    protected $model;
    protected $viewsDomain = 'dashboard.brands.';
    use UploadFile;

    public function __construct()
    {
        $this->model = new Brand();

        $this->middleware('permission:brands-list|brands-create|brands-edit|brands-delete', ['only' => ['index', 'show']]);
        $this->middleware('permission:brands-create', ['only' => ['create', 'store']]);
        $this->middleware('permission:brands-edit', ['only' => ['edit', 'update']]);
        $this->middleware('permission:brands-delete', ['only' => ['destroy']]);

    }

    private function view($view, $params = [])
    {
        return view($this->viewsDomain . $view, $params);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request , BrandService $brandService)
    {
        $items = $brandService->index($request->all()) ;
        return $this->view('index', compact('items'));
    }

    public function store( BrandStoreRequest $request, BrandService $brandService )
    {
        $brandService->store($request->validated()) ;
        flash(__('messages.added_successfully'))->success();
        return back();
    }

    public function update( BrandUpdateRequest $request, $id , BrandService $brandService)
    {
        $brandService->update($request->validated() ,$id ) ;
        flash(__('messages.updated_successfully'))->success();
        return back();
    }

    public function destroy($id , BrandService $brandService)
    {
        $isDeleted = $brandService->delete($id);
        if ( $isDeleted ) {
            flash(__('messages.deleted_successfully'))->success();
        }else{
            flash(__('messages.cant_deleted'))->error();
        }
        return back();

    }

    public function updateAxios( Request $request , $id )
    {
        $item = $this->model->findOrFail($id);
        $data = [] ;
        foreach ( $request->all() as $key => $value )
        {
            $data = [ $key => $value ] ;
        }
        $item->update($data);
        return response()->json(["status" => true , "message" => __('messages.updated_successfully') ]) ;
    }
}

app/Http/Controllers/Dashboard/ComplaintSuggestionController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Http\Requests\Dashboard\ComplaintSuggestion\ComplaintReplayRequest;
use App\Http\Requests\Dashboard\SurveyQuestion\SurveyQuestionUpdateRequest;
use App\Http\Requests\Dashboard\SurveyQuestion\SurveyQuestionStoreRequest;
use App\Models\ComplaintSuggestion;
use App\Models\SurveyQuestion;
use App\Enums\StatusesEnum;
use App\Services\ComplaintSuggestionService;
use App\Services\SurveyQuestionService;
use Illuminate\Http\Request;

class ComplaintSuggestionController extends Controller
{
    protected $model;
    protected $viewsDomain = 'dashboard.complaintSuggestion.';

    public function __construct()
    {
        $this->model = new ComplaintSuggestion();
        /**/
        //$this->middleware('permission:complaintSuggestion-list|survey-create|survey-edit|survey-delete', ['only' => ['index', 'show']]);
        $this->middleware('permission:complaints-suggestions-list', ['only' => [ 'index']]);
        $this->middleware('permission:complaints-suggestions-replay', ['only' => ['replay']]);


    }

    private function view($view, $params = [])
    {
        return view($this->viewsDomain . $view, $params);
    }

    public function index( Request $request , ComplaintSuggestionService $complaintSuggestionService)
    {
        $items = $complaintSuggestionService->index( $request->all() ) ;
        return $this->view('index', compact('items'));
    }

    public function replay( Request $request, ComplaintSuggestionService $complaintSuggestionService )
    {
        $complaintSuggestionService->replay($request->all()) ;
        flash(__('messages.added_successfully'))->success();
        return back();
    }
}

app/Http/Controllers/Dashboard/PaymentRequestController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Http\Requests\Dashboard\Brand\BrandStoreRequest;
use App\Http\Requests\Dashboard\Brand\BrandUpdateRequest;
use App\Models\Brand;
use App\Models\Client;
use App\Models\Order;
use App\Services\BrandService;
use App\Services\OrderService;
use App\Traits\PaymentMethodTrait;
use App\Traits\UploadFile;
use Illuminate\Http\Request;

class PaymentRequestController extends Controller
{
    protected $model;
    protected $viewsDomain = 'dashboard.orders.';
    use UploadFile;
    use PaymentMethodTrait ;

    public function __construct()
    {
//        $this->middleware('permission:brands-list|brands-create|brands-edit|brands-delete', ['only' => ['index', 'show']]);
        $this->middleware('permission:payment-requests-list', ['only' => ['paymentRequest']]);
    }

    private function view($view, $params = [])
    {
        return view($this->viewsDomain . $view, $params);
    }

    public function paymentRequest(Request $request , OrderService $orderService)
    {
        $items = Order::where("status" , 7)->orderBy('id', 'DESC')->paginate();
        $clients = Client::client()->get();
        $providers = Client::provider()->get();
        $paymentMethods = $this->getPaymentMethodsAttribute() ;

        return $this->view('paymentRequest', compact('clients' ,'providers','items' ,'paymentMethods'));
    }
}

resources/views/dashboard/paymentRequest/index.blade.php
@extends('dashboard.layouts.app', ['title' => __('app.titles.orders')])
@section('content')
    <div class="row">
        <div class="col-lg-12 col-xl-12 stretch-card">
            <div class="card mb-3">
                <div class="card-body filter">
                    <form class="filter_form">
                        <div class="form-group row">
                            {{--<label for="filter_type" class="col-sm-2 col-form-label"> {{__('app.order_type')}}  : </label>--}}
                            {{--<div class="col-sm-2">--}}
                                {{--<select class="form-control select2" name="type" id="filter_type">--}}
                                    {{--<option value=""> -- {{__("app.choose")}} -- </option>--}}

                                    {{--<option value="1"> ملغي </option>--}}
                                    {{--<option value="2"> جاري </option>--}}
                                    {{--<option value="3"> انتهي </option>--}}
                                {{--</select>--}}
                            {{--</div>--}}


                            <label for="period" class="col-sm-2 col-form-label"> {{__('app.duration')}} : </label>
                            <div class="col-sm-3">
                                <select class="form-control select2" name="type" id="period">
                                    <option value=""> -- {{__("app.choose")}} -- </option>
                                    <option value="1"> شهر </option>
                                    <option value="2"> 2 شهر </option>
                                    <option value="2"> 3 شهور </option>
                                    <option value="3"> سنه </option>
                                </select>
                            </div>

                            <label for="place" class="col-sm-2 col-form-label"> {{__('app.client')}} :  </label>
                            <div class="col-sm-2">
                                <select class="form-control select2" name="client_id">
                                    <option value=""> -- {{__("app.choose")}} -- </option>
                                    @foreach( $clients as $client )
                                        <option value="{{$client->id}}"
                                            @if($client->id == request("client_id"))
                                                selected
                                            @endif
                                        > {{$client->FULLNAME}} </option>
                                    @endforeach
                                </select>
                            </div>

                            <label for="place" class="col-sm-2 col-form-label"> {{__('app.provider')}} </label>
                            <div class="col-sm-2">
                                <select class="form-control select2" name="provider_id">
                                    <option value=""> -- {{__("app.choose")}} -- </option>
                                    @foreach( $providers as $provider )
                                        <option value="{{$provider->id}}"
                                                @if($provider->id == request("provider_id"))
                                                selected
                                                @endif
                                        > {{$provider->FULLNAME}} </option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="col-sm-2">
                                <button type="submit" class="btn btn-primary submit"> {{__('app.search')}} </button>
                                <button type="button" class="btn clear_search btn-danger btn-icon aligner">
                                    <i class="link-icon" data-feather="refresh-cw"></i>
                                </button>

                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-lg-12 col-xl-12 stretch-card">
            <div class="card">
                @include("dashboard.includes.info_page",['items' => $items ])
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-hover mb-0">
                            <thead>
                            <tr>
                                <th class="pt-0">#</th>
                                <th class="pt-0"> {{__('app.order_id')}} </th>
                                <th class="pt-0"> {{__('app.service')}} </th>
                                <th class="pt-0"> {{__('app.service_technician')}} </th>
                                <th class="pt-0"> {{__('app.service_requester')}} </th>
                                <th class="pt-0"> {{__('app.price')}} </th>
                                <th class="pt-0"> {{__('app.processes')}} </th>
                            </tr>
                            </thead>
                            <tbody>
                            @forelse( $items as $item )
                                <tr>
                                    <td> {{ $loop->iteration }} </td>
                                    <td> {{ $item->id }} </td>

                                    <td>
                                        <strong>
                                            {{ optional( optional($item->service)->parentItem )->name }}
                                        </strong>
                                            /
                                            {{ optional($item->service)->name }}
                                    </td>

                                    <td>
                                        <div style="width: 200px">
                                            <select class="form-control select2 technician_item" data-route="{{route("order.assign")}}" data-id="{{$item->id}}" name="client_id" >
                                                <option value=""> -- {{__("app.choose")}} -- </option>
                                                @foreach( $providers as $provider )
                                                    <option value="{{$provider->id}}"
                                                         @if( $provider->id == $item->provider_id )
                                                             selected
                                                         @endif
                                                    > {{$provider->full_name}} </option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </td>

                                    <td> {{ optional($item->client)->full_name }} </td>
                                    <td> {{ $item->price }} </td>
                                    <td>
                                        {{--@can("orders-show")--}}
                                        <a href="{{route("orders.show" , $item->id)}}"
                                           class="btn btn-success btn-icon aligner">
                                            <i data-feather="eye"></i>
                                        </a>

                                        {{--<form style="display: inline-block" method="post"--}}
                                              {{--action="{{route("orders.destroy", $item->id)}}"--}}
                                              {{--onsubmit="return confirm('هل أنت متأكد من الحذف؟')">--}}
                                            {{--@method('delete')--}}
                                            {{--@csrf--}}
                                            {{--<button type="submit" class="btn btn-danger btn-icon aligner"><i--}}
                                                    {{--data-feather="trash"></i></button>--}}
                                        {{--</form> --}}
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="8" class="danger text-center">{{__('app.no_data')}}</td>
                                </tr>
                            @endforelse
                            </tbody>
                        </table>
                        <div class="text-center">
                            {!! $items->appends(request()->query())->render() !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')

    <script>
        $('.technician_item').change(function(){

            let id = $(this).data('id') ,
                val = $(this).val() ,
                route = $(this).data('route') ;

            axios.post(route, {
                val  : val ,
                id   : id
            }).then((response) => {
                console.log("response >> " , response )
                if (response.data.status == true) {
                    $("#messages_").empty().append("<p class='alert alert-success'> {{ __('app.assigned_to_order') }} </p>")
                    setTimeout(function() {
                        $("#messages_").empty()
                    }, 2000);
                }
            })
        });
    </script>

@endpush