routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use Illuminate\Support\Facades\Mail;

use GuzzleHttp\Client;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/sas', function () {
    $total = 48 ;
    return \App\Models\LoyaltyPoint::where("num_sar" , "<=" , $total)
        ->orderBy("num_sar" , "DESC")
        ->where("active","active")
        ->first();
});

Route::get('/curl', function () {

    $firebaseDatabaseURL = 'https://kafo-8f75c-default-rtdb.firebaseio.com';
    $firebaseSecret = 'kBU5uUbdIGz8AXaHu19EVTR3N1EFcLOOtaE57M2w	';

    $client = new Client();

    // Example data to be pushed to Firebase
    $data = [
        'event_name' => 'Example Event',
        'timestamp' => now()->toDateTimeString(),
    ];

    // Make a PUT request to push data to Firebase
    $response = $client->put($firebaseDatabaseURL . 'events.json?auth=' . $firebaseSecret, [
        'json' => $data,
    ]);

    // Check the response for success or handle errors
    if ($response->getStatusCode() === 200) {
        return response()->json(['message' => 'Event pushed to Firebase']);
    } else {
        return response()->json(['error' => 'Failed to push event to Firebase'], $response->getStatusCode());
    }
});

Route::get('/change-order/{id}/{status}', function ( \Illuminate\Http\Request $request ) {

    $id =  $request->id ;
    $status =  $request->status ;

    $order = \App\Models\Order::where("id",$id)->first();
    $order->status = $status ;
    $order->save();
    return "Done";
});


Route::get('/test-query', function () {
//    $lat =  "75.2343743294477";
//    $lng = "-78.37305343098593";

    $lat =  "30.956465";
    $lng = "31.2503834";

    $results = \Illuminate\Support\Facades\DB::table('cities')
        ->whereNotNull('zone_polygon')
        ->where('zone_polygon', 'LIKE', 'POLYGON%')
        ->whereRaw("ST_Intersects(ST_GEOMFROMTEXT('POINT(".$lat." ".$lng.")'), ST_GEOMFROMTEXT(zone_polygon))")
        ->get();

    return $results ;

    /*
     * SELECT * FROM cities
WHERE (zone_polygon IS NOT NULL)
AND (zone_polygon LIKE 'POLYGON%')
AND ST_Intersects(ST_GEOMFROMTEXT('POINT(75.2343743294477 -78.37305343098593)'), ST_GEOMFROMTEXT(zone_polygon));
     */

   // $providers = \Illuminate\Support\Facades\DB::select( \Illuminate\Support\Facades\DB::raw(
  //      "SELECT * FROM `citis` WHERE (`zone_polygon` IS NOT NULL) AND (`zone_polygon` LIKE  'POLYGON%')
//AND ST_Intersects(ST_GEOMFROMTEXT('POINT('+$lng -78.37305343098593)'), ST_GEOMFROMTEXT(zone_polygon));
//ST_Intersects(GeomFromText(extra), GeomFromText('POINT(".$lat." ".$lng.")'))") );
    $providers = \Illuminate\Support\Facades\DB::select(\Illuminate\Support\Facades\DB::raw("SELECT * FROM cities
WHERE (zone_polygon IS NOT NULL)
AND (zone_polygon LIKE 'POLYGON%')
AND ST_Intersects(ST_GEOMFROMTEXT('POINT(30.0333 30.0333)'), ST_GEOMFROMTEXT(zone_polygon));"));
    return $providers ;
});


Route::get('/ddd', function () {
    $user = \App\Models\User::first() ;
    $orderID = 3 ;
    $status = "danger" ;
    $statusProvider = "تم رفض الطلب من قبل الفني ' محمد عزت راشد '" ;
    $user->notify(new \App\Notifications\UserNotification($orderID ,$status , $statusProvider));
    return "Sdsds" ;
});


Route::get('/dd1111d', function () {
//    $user = \App\Models\User::first() ;
//    $orderID = 3 ;
//    $status = "danger" ;
//    $statusProvider = "تم رفض الطلب من قبل الفني ' محمد عزت راشد '" ;
//    $user->notify(new \App\Notifications\UserNotification($orderID ,$status , $statusProvider));
//    return "Sdsds" ;

    $notes = \App\Models\Notification::where("notifiable_type" , "App\Models\User")->get() ;
     $data = $notes[1] ;
    return json_decode($data)->data ;
});



Route::get('/qqq', function () {
    $dateTime = date('Y-m-d H:i:s') ;
    return \Carbon\Carbon::parse(\Carbon\Carbon::parse($dateTime)->setTimezone('UTC')->format('Y-m-d H:i:s'), 'UTC');
});

Route::get('language/{locale}', function ($locale) {
    app()->setLocale($locale);
    session()->put('locale', $locale);
    return redirect()->back();
})->name("change-lang");
//
//Route::get('/send-notification', function () {
//    $data = date('Y-m-d H:i:s') ;
////    return $data ;
//    $da = \Carbon\Carbon::parse(Carbon\Carbon::parse($data)->setTimezone('UTC')->format('Y-m-d H:i:s'), 'UTC');
//
//
//    return $da ;
//    $users = \App\Models\Client::get() ;
//    \Illuminate\Support\Facades\Notification::send($users , new \App\Notifications\AdminNotification());
//});
//
Route::get('/send-firebaseNotification', function () {
    $player_id = "e8a4M26HXkzEl23wgXy9vq:APA91bHySKTfxYgVyl9sKQ3TMmORJzk3K-K0VVNIow001uFakn4fhnMpMvW1ZxXi_hO4mpdrR0bVn58uySvCQ9IIxD1gH6fY0SMt7P_JEG5XpbETCos-KIIY4E4_ooUwnTBMRb-v0Bdq";
    $notify_fire = new \App\FirebaseNotification();

    $msg_ar = " أهلا صديقي سعيد" ;
    try {
        $res = $notify_fire->sendNote([$player_id], 'Kafo', $msg_ar,"تجريب عنوان",1);
    } catch (\Exception $e) {
        // Handle the exception (log it, display an error message, etc.)
        \Log::error('Email sending failed: ' . $e->getMessage());
        dd(">>",$e->getMessage()) ;
    }
    return $res;
});

Route::get('/send-email-121', function () {

    return Mail::raw('This is a test email', function($message) {
        $message->to('mahmoud.ragaey.99@gmail.com');
        $message->subject('Test Email');
    });

    return $tt ;

//$to = "melzaiady@yahoo.co.uk";
//$to = "mahmoud.ragaey.99@gmail.com";
//$subject = "HTML email";
//
//$message = "
//<html>
//<head>
//<title>HTML email</title>
//</head>
//<body>
//<p>This email contains HTML Tags!</p>
//<table>
//<tr>
//<th>Firstname</th>
//<th>Lastname</th>
//</tr>
//<tr>
//<td>John</td>
//<td>Doe</td>
//</tr>
//</table>
//</body>
//</html>
//";

// Always set content-type when sending HTML email
//$headers = "MIME-Version: 1.0" . "\r\n";
//$headers .= "Content-type:text/html;charset=UTF-8" . "\r\n";
//
//// More headers
//$headers .= 'From: <info@mragaey.com>' . "\r\n";
//
//mail($to,$subject,$message,$headers);

    return "Done"  ;
});

Route::get('/send-email-21', function () {
    $email = "mahmoud.ragaey.99@gmail.com" ;
    $subject ="subject" ;
    $text = "text" ;
    $phone = "090090909" ;
    $data = array('email' => $email, 'subject' => $subject, 'body' => $text, 'mobile'=>$phone);

    //********* end send email
    $aa = Mail::send('emails_items.contact', $data, function($message) use ($data) {
        $message->from($data['email']);
        $message->to('mahmoud.ragaey.99@gmail.com');
        $message->subject($data['subject']);
    });

    return $aa ;



    $em = "mahmoud.ragaey.99@gmail.com" ;
    $name  = " name" ;
    return \Illuminate\Support\Facades\Mail::to($em)->send(new \App\Mail\ContactEmail($em , $name));

    return "sasa";

    $toAdminMail= "your_admin_email@gmail.com";
    $message  = " Check Contact Form" ;


    \Illuminate\Support\Facades\Mail::to($toAdminMail)->send(new \App\Notifications\ContactMessage($message , $name));

    return "DONE" ;


    $provider = \App\Models\Client::where("id" ,54)->first();
    $name ="Yaaarb" ;
    $order_id =11 ;
    $message = 'new request been sent to you and awaiting your approval of the request :: ' .$name .' :: order id ::'.$order_id;
    $titleNote =  'app.note_new_request' ;
    $provider->notify(new \App\Notifications\ClientNotification($message , $titleNote));
    return "Done" ;
});

Route::get('/hyperPaypayment-23', function () {
    $id = "B5EAB7D8FD0D9BEEDC738820C043833A.uat01-vm-tx01" ;

    $url = "https://test.oppwa.com/v1/checkouts/".$id."/payment?entityId=8a8294174d0595bb014d05d82e5b01d2";
//    $url .= "";

    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_HTTPHEADER, array(
        'Authorization:Bearer OGE4Mjk0MTc0ZDA1OTViYjAxNGQwNWQ4MjllNzAxZDF8OVRuSlBjMm45aA=='));
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);// this should be set to true in production
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    $responseData = curl_exec($ch);
    if(curl_errno($ch)) {
        return curl_error($ch);
    }
    curl_close($ch);
    return $responseData;
});

Route::get('/hyperPaypayment-22', function () {

    //visa 8ac7a4c78694e687018697314f3e02f4
    // 8ac7a4c78694e68701869731bae102f9

//    return config("settings.payments.visaEntityID") ;

    $price = 92.00;

    $url = config('settings.payments.url')."/checkouts";
    $data = "entityId=".config('settings.payments.visaEntityID')."" .
        "&amount=".$price.
        "&currency=".config('settings.payments.currency')."".
        "&paymentType=DB";

    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_HTTPHEADER, array(
        'Authorization:Bearer OGE4Mjk0MTc0ZDA1OTViYjAxNGQwNWQ4MjllNzAxZDF8OVRuSlBjMm45aA=='));
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false); // this should be set to true in production
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    $responseData = curl_exec($ch);

    if(curl_errno($ch)) {
        return curl_error($ch);
    }
    curl_close($ch);

    return  json_decode($responseData);

    return $responseData;

});


Route::get('/hyperPaypayment-21', function () {
    $user = \App\Models\Client::first();

    $price = 200;
    $amount = $price;// $request->amount ;
    //
    $package_id = 2 ;
    $merchantTransactionId = $user->id.strtotime(date("Y-m-d H:m:s"));
    $userID = $user->id;
    //
    $UserName= $user->name;

app/Models/Client.php
<?php

namespace App\Models;

use App\Traits\ActiveStatusTrait;
use Illuminate\Database\Eloquent\Factories\HasFactory;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\Builder;


use App\Enums\ClientTypeEnum;
use Laravel\Sanctum\HasApiTokens;

class Client extends Authenticatable
{
    use HasFactory , HasApiTokens, Notifiable ,SoftDeletes, ActiveStatusTrait;

    protected $guarded = ['id'] ;

    public function scopeProvider($query)
    {
        return $query->where('type', ClientTypeEnum::PROVIDER->value );
    }

    public function scopeClient($query)
    {
        return $query->where('type', ClientTypeEnum::CLIENT->value );
    }

    public function getFullNameAttribute()
    {
        return $this->first_name ." ". $this->last_name ;
    }

    public function getAvatarImageAttribute()
    {
        if ( $this->avatar ){
            return asset($this->avatar );
        }
        return  "/kafo-development/assets/images/logo-sm.png" ;
    }

    public function getClientRateAvgAttribute()
    {
        return $this->providerOrders()->avg('client_rate');
    }

    public function clientOrders(){
        return $this->hasMany(Order::class , "client_id" ) ;
    }

    public function providerOrders(){
        return $this->hasMany(Order::class , "provider_id" ) ;
    }

    public function getProviderHoursOrdersAttribute(){
        $completionTimes = [];
        foreach ( $this->providerOrders()->get() as $key => $item ) {
            $completionTimes[] = $item->completion_time ;
        }
        return array_sum($completionTimes) ;
    }

    public function setPhoneAttribute($value){
        $this->attributes['phone'] = str_replace(' ', '', $value);
    }

    public function scopeFilter(Builder $query, $filter)
    {
        $filter->filter($query);
    }


    public function city()
    {
        return $this->belongsTo(City::class) ;
    }
}

app/Http/Controllers/Api/Client/AddressClientController.php
<?php

namespace App\Http\Controllers\Api\Client;

use App\Http\Controllers\Api\BaseController;
use App\Http\Resources\AddressClientResource;
use App\Models\AddressClient;
use App\Enums\OrderStatusEnum;
use App\Models\City;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Request as UserRequest;

class AddressClientController extends BaseController
{

    public function __construct()
    {
        $this->model = new AddressClient();

    }

    public function index( )
    {
        $user = UserRequest::user() ;
        $items = AddressClient::where("client_id",$user->id)->get();
        $items = AddressClientResource::collection($items) ;
        return $this->sendResponse($items, __("messages.successfully"));
    }

    public function store( Request $request  )
    {
        $user = UserRequest::user() ;
        $res = $this->checkCity($request->lat ,  $request->lon) ;

        if ( !$res ) {
            $error = __("app.no_city");
            return $this->sendError($error);
        }


        AddressClient::create([
            "client_id" => $user->id ,
            "lat" => $request->lat ,
            "lon" => $request->lon ,
            "city_id" => $request->city_id ,
            "address" => $request->address ,
            "region" => $request->region
        ]);
        return $this->sendResponse([], __("messages.added_successfully"));
    }

    public function delete( $id )
    {
        $user = UserRequest::user() ;
        $item = AddressClient::where(["client_id"=> $user->id , "id" => $id])->first();
        if ($item){
            $item->delete();
            return $this->sendResponse([], __("messages.deleted_successfully"));
        } else {
            return $this->sendError( __("messages.not_found"));
        }
    }


    public function update( Request $request, $id )
    {
        $user = UserRequest::user() ;
        $item = AddressClient::where(["client_id"=> $user->id , "id" => $id])->first();

        if ( $item ){
            $item->lat = $request->lat ;
            $item->lon = $request->lon ;
            $item->city_id = $request->city_id ;
            $item->address = $request->address ;
            $item->region = $request->region ;
            $item->save();
            return $this->sendResponse([], __("messages.updated_successfully"));
        }
        return $this->sendError( __("messages.not_found"));
    }



    private function checkCity( $lat , $lng )
    {
        if ( $lat && $lng ) {
            $city = City::query()
                ->whereNotNull('zone_polygon')
                ->where('zone_polygon', 'LIKE', 'POLYGON%')
                ->whereRaw("ST_Intersects(ST_GEOMFROMTEXT('POINT(".$lat." ".$lng.")'), ST_GEOMFROMTEXT(zone_polygon))")
                ->first();

            if ($city){
                return true ;
            }
            return false ;
        }

        return false ;
    }

}

app/Http/Controllers/Dashboard/BrandController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Http\Requests\Dashboard\Brand\BrandStoreRequest;
use App\Http\Requests\Dashboard\Brand\BrandUpdateRequest;
use App\Models\Brand;
use App\Services\BrandService;
use App\Traits\UploadFile;
use Illuminate\Http\Request;

class BrandController extends Controller
{
    protected $model;
    protected $viewsDomain = 'dashboard.brands.';
    use UploadFile;

    public function __construct()
    {
        $this->model = new Brand();

        $this->middleware('permission:brands-list|brands-create|brands-edit|brands-delete', ['only' => ['index', 'show']]);
        $this->middleware('permission:brands-create', ['only' => ['create', 'store']]);
        $this->middleware('permission:brands-edit', ['only' => ['edit', 'update']]);
        $this->middleware('permission:brands-delete', ['only' => ['destroy']]);

    }

    private function view($view, $params = [])
    {
        return view($this->viewsDomain . $view, $params);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request , BrandService $brandService)
    {
        $items = $brandService->index($request->all()) ;
        return $this->view('index', compact('items'));
    }

    public function store( BrandStoreRequest $request, BrandService $brandService )
    {
        $brandService->store($request->validated()) ;
        flash(__('messages.added_successfully'))->success();
        return back();
    }

    public function update( BrandUpdateRequest $request, $id , BrandService $brandService)
    {
        $brandService->update($request->validated() ,$id ) ;
        flash(__('messages.updated_successfully'))->success();
        return back();
    }

    public function destroy($id , BrandService $brandService)
    {
        $isDeleted = $brandService->delete($id);
        if ( $isDeleted ) {
            flash(__('messages.deleted_successfully'))->success();
        }else{
            flash(__('messages.cant_deleted'))->error();
        }
        return back();

    }

    public function updateAxios( Request $request , $id )
    {
        $item = $this->model->findOrFail($id);
        $data = [] ;
        foreach ( $request->all() as $key => $value )
        {
            $data = [ $key => $value ] ;
        }
        $item->update($data);
        return response()->json(["status" => true , "message" => __('messages.updated_successfully') ]) ;
    }
}

resources/views/dashboard/clients/show.blade.php
@extends('dashboard.layouts.app', ['title' => __('app.clients.show')])
@section('content')
    @push('button')
        <div class="d-flex align-items-center flex-wrap text-nowrap">
            <a href="{{route('clients.index')}}" class="btn btn-primary">
                <i data-feather="skip-back"></i>
            </a>
        </div>
    @endpush
    <div class="row">
        <div class="col-lg-12 col-xl-12 ">
            <div class="card">
                <div class="card-body resize_section">
                    <div class="row">
                        <div class="col-md-12 text-center">
                            <img src="{{ $item->avatar_image }}" class="avatar" />
                        </div>
                        <div class="col-md-2 mb-3">
                            {{__('app.name')}} :
                        </div>
                        <div class="col-md-10 mb-3">
                            {{$item->full_name}}
                        </div>

                        <div class="col-md-2 mb-3">
                            {{__('app.email')}} :
                        </div>
                        <div class="col-md-4 mb-3">
                            {{$item->email}}
                        </div>

                        <div class="col-md-2 mb-3">
                            {{__('app.phone')}} :
                        </div>
                        <div class="col-md-4 mb-3 phone">
                            {{$item->phone}}
                        </div>
                        <div class="col-md-2 mb-3">
                            {{__('app.date_joining')}} :
                        </div>
                        <div class="col-md-4 mb-3">
                            {{$item->created_at}}
                        </div>

                        <div class="col-md-2 mb-3">
                            {{__('app.balance')}} :
                        </div>
                        <div class="col-md-4 mb-3">
                            {{$item->balance}}
                        </div>

                        <div class="col-md-2 mb-3">
                            {{__('app.block_statue')}} :
                        </div>
                        <div class="col-md-4 mb-3">
                            @if( $item->block_status == "block" )
                                {{__('app.block')}}
                            @else
                                {{__('app.unblock')}}
                            @endif
                        </div>


                        @if( $item->block_status == "block" )
                        <div class="col-md-2 mb-3">
                            {{__('app.reason')}} :
                        </div>
                        <div class="col-md-4 mb-3">
                            {{$item->block_reason}}
                        </div>
                        @endif
                    </div>
                </div>
            </div>
            {{--Orders--}}
            <div class="card mt-4">
                <div class="card-body resize_section">
                    <div class="row">
                        <div class="col-md-12">
                            <h5 class="mb-4"> {{__('app.client_requests')}} </h5>
                        </div>
                        <div class="col-md-12">

                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table table-hover mb-0">
                                        <thead>
                                        <tr>
                                            <th class="pt-0"> {{__('app.order_id')}} </th>
                                            <th class="pt-0"> {{__('app.total')}} </th>
                                            <th class="pt-0"> {{__('app.payment_type')}} </th>
                                            <th class="pt-0"> {{__('app.payment_status')}} </th>

                                            <th class="pt-0"> {{__('app.processes')}} </th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @forelse( $orders as $order )
                                            <tr>
                                                <td> {{ $order->id }}</td>
                                                <td> {{ $order->total }} </td>
                                                <td>
                                                    @if( $order->method_payment )
                                                        {{$order->payment_methods[$order->method_payment] }}
                                                    @endif
                                                </td>
                                                <td> {{ $order->is_paid ? __("app.paid"):__("app.not_paid") }} </td>
                                                <td>
                                                    <a href="{{route("orders.show", $order->id)}}"
                                                       class="btn btn-success btn-icon aligner ">
                                                        <i data-feather="eye"></i>
                                                    </a>
                                                </td>
                                            </tr>
                                        @empty
                                            <tr>
                                                <td colspan="8" class="danger text-center">
                                                    {{__('app.no_requests')}}
                                                </td>
                                            </tr>
                                        @endforelse
                                        </tbody>
                                    </table>
                                    {{--<div class="text-center">--}}
                                        {{--{!! $items->appends(request()->query())->render() !!}--}}
                                    {{--</div>--}}
                                </div>
                            </div>

                            {{--@forelse( $orders as $order )--}}
                                {{--<div class="row">--}}
                                    {{--<div class="col-md-2 mb-3">--}}
                                        {{--{{__('app.service_name')}} :--}}
                                    {{--</div>--}}
                                    {{--<div class="col-md-10 mb-3">--}}
                                        {{--{{optional( $order->service )->name}}--}}
                                    {{--</div>--}}
                                {{--</div>--}}
                                {{--<div class="row">--}}
                                    {{--<div class="col-md-2 mb-3">--}}
                                        {{--{{__('app.price')}} :--}}
                                    {{--</div>--}}
                                    {{--<div class="col-md-4 mb-3">--}}
                                        {{--{{$order->price ?? "--"}}--}}
                                    {{--</div>--}}

                                    {{--<div class="col-md-2 mb-3">--}}
                                        {{--{{__('app.service_date')}} :--}}
                                    {{--</div>--}}
                                    {{--<div class="col-md-4 mb-3">--}}
                                        {{--{{$order->service_date ?? "--"}}--}}
                                    {{--</div>--}}
                                {{--</div>--}}
                                    {{----}}
                                {{--<div class="row">--}}
                                    {{--<div class="col-md-2 mb-3">--}}
                                        {{--{{__('app.description')}} :--}}
                                    {{--</div>--}}
                                    {{--<div class="col-md-4 mb-3">--}}
                                        {{--{{$order->description  ?? "--"}}--}}
                                    {{--</div>--}}


                                    {{--<div class="col-md-2 mb-3">--}}
                                        {{--{{__('app.created_at')}} :--}}
                                    {{--</div>--}}
                                    {{--<div class="col-md-4 mb-3">--}}
                                        {{--{{$order->created_at}}--}}
                                    {{--</div>--}}
                                {{--</div>--}}

                                {{--<div class="row">--}}
                                    {{--<div class="col-md-2 mb-3">--}}
                                        {{--{{__('app.client_comment')}} :--}}
                                    {{--</div>--}}
                                    {{--<div class="col-md-4 mb-3">--}}
                                        {{--{{$order->client_comment  ?? "--"}}--}}
                                    {{--</div>--}}


                                    {{--<div class="col-md-2 mb-3">--}}
                                        {{--{{__('app.provider_rate')}} :--}}
                                    {{--</div>--}}
                                    {{--<div class="col-md-4 mb-3">--}}
                                        {{--{{$order->provider_rate}}--}}
                                    {{--</div>--}}
                                {{--</div>--}}
                                {{--<hr>--}}
                            {{--@empty--}}
                                {{--<div class="text-danger text-center">--}}
                                    {{--{{__('app.no_requests')}}--}}
                                {{--</div>--}}
                            {{--@endforelse--}}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection


@push("styles")
    <style>
            /*.resize_section .col-md-2 {*/
                /*max-width: 11%;!**!*/
            /*}*/

            /*.resize_section .col-md-4 {*/
                /*max-width: 46%;*/
            /*}*/
    </style>
@endpush